services:
  web:
    container_name: web
    build: web
    ports:
      - 4321:4321

  content:
    container_name: content
    build: content
    depends_on:
      - db
    volumes:
      - content:/var/www/html/web/app/uploads
    ports:
      - 8080:80

  db:
    container_name: db
    image: mariadb:10.11.10-jammy
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.2-apache
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - 3380:80

volumes:
  content:
  db: