services:
  content:
    build: content
    depends_on:
      - db
    volumes:
      - content:/var/www/html/web/app/uploads

  db:
    image: mariadb:10.11.10-jammy
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1

volumes:
  content:
  db: