services:
  content:
    container_name: content
    ports:
      - 8080:80

  db:
    container_name: db
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.2-apache
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - 3380:80
