services:
  workspace:
    container_name: workspace
    depends_on:
      - db
      - phpmyadmin
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: ["sleep", "infinity"]

  db:
    container_name: db
    image: mariadb:10.11.10-jammy
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: workspace
      MYSQL_PASSWORD: workspace
      MYSQL_DATABASE: workspace
      MYSQL_RANDOM_ROOT_PASSWORD: 1

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin:5.2.2-apache
    restart: unless-stopped
    environment:
      APACHE_PORT: 4323
      PMA_HOST: 127.0.0.1
      PMA_PORT: 3306
      PMA_USER: workspace
      PMA_PASSWORD: workspace
    network_mode: service:db

volumes:
  db_data:
