service: content
image: sngrstudio/news-template-content

servers:
  - 103.150.101.64

builder:
  arch: amd64
  cache:
    type: gha
    options: mode=max
    image: news-template-content-builder

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: server

proxy:
  ssl: true
  host: content.103.150.101.64.sslip.io
  app_port: 80
  healthcheck:
    path: /wp/wp-admin/images/wordpress-logo.svg

accessories:
  db:
    image: mariadb:10.11.10-jammy
    roles:
      - web
    env:
      clear:
        MYSQL_RANDOM_ROOT_PASSWORD: 1
      secret:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    directories:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.2-apache
    roles:
      - web
    env:
      clear:
        PMA_HOST: content-db
      secret:
        - PMA_USER
        - PMA_PASSWORD
    proxy:
      ssl: true
      host: phpmyadmin.103.150.101.64.sslip.io
      app_port: 80