services:
    content:
        name: Content Service
        description: Run WordPress-based content service
        commands:
            start: |
                php -S 0.0.0.0:4322 -t ./content/web
        triggeredBy:
            - postEnvironmentStart
