services:
  db:
    name: Database Service
    commands:
      start: |
        docker compose -f 'docker-compose.yml' up -d --build 'db'
    triggeredBy:
      - postEnvironmentStart

  phpmyadmin:
    name: PHPMyAdmin
    commands:
      start: |
        docker compose -f 'docker-compose.yml' up -d --build 'phpmyadmin'
    triggeredBy:
      - manual